"""
Error Codes expected from the server.
Keep sorted by error code number. No duplicates.
"""


class ErrorCode(int):
    """Distinct type for error codes, so expected values can distinguish errors from results."""
    pass


DIVIDE_BY_ZERO_ERROR = ErrorCode(2)
TYPE_MISMATCH_ERROR = ErrorCode(14)
EXPRESSION_TYPE_MISMATCH_ERROR = ErrorCode(16020)
MODULO_ZERO_REMAINDER_ERROR = ErrorCode(16610)
MODULO_NON_NUMERIC_ERROR = ErrorCode(16611)
MORE_THAN_ONE_DATE_ERROR = ErrorCode(16612)
ABS_OVERFLOW_ERROR = ErrorCode(28680)
LOG_NON_NUMERIC_VALUE_ERROR = ErrorCode(28756)
LOG_NON_NUMERIC_BASE_ERROR = ErrorCode(28757)
LOG_NON_POSITIVE_VALUE_ERROR = ErrorCode(28758)
LOG_INVALID_BASE_ERROR = ErrorCode(28759)
LOG10_NON_POSITIVE_INPUT_ERROR = ErrorCode(28761)
POW_NON_NUMERIC_BASE_ERROR = ErrorCode(28762)
POW_NON_NUMERIC_EXP_ERROR = ErrorCode(28763)
POW_BASE_ZERO_EXP_NEGATIVE_ERROR = ErrorCode(28764)
NON_NUMERIC_TYPE_MISMATCH_ERROR = ErrorCode(28765)
LN_NON_POSITIVE_INPUT_ERROR = ErrorCode(28766)
MODULO_DECIMAL128_ZERO_REMAINDER_ERROR = ErrorCode(5733415)
