"""$toString type rejection tests: special-form inputs not covered by bson_type_validator."""

import pytest

from documentdb_tests.compatibility.tests.core.operator.expressions.utils.expression_test_case import (  # noqa: E501
    ExpressionTestCase,
)
from documentdb_tests.compatibility.tests.core.operator.expressions.utils.utils import (
    assert_expression_result,
    execute_expression,
)
from documentdb_tests.framework.error_codes import CONVERSION_FAILURE_ERROR
from documentdb_tests.framework.parametrize import pytest_params

# Property [Type Rejection — Special Forms]: cases not generated by bson_type_validator in
# test_toString_return_type.py because they require specific expression forms or subtypes.
# The sample BSON type sweep (MinKey, MaxKey, Timestamp, Regex, Code, Object) is covered
# by test_toString_type_rejection in test_toString_return_type.py.
TOSTRING_TYPE_ERROR_TESTS: list[ExpressionTestCase] = [
    ExpressionTestCase(
        "type_nested_array",
        msg="Nested array via $literal is a conversion failure",
        expression={"$toString": {"$literal": [[1, 2], [3, 4]]}},
        error_code=CONVERSION_FAILURE_ERROR,
    ),
    ExpressionTestCase(
        "type_runtime_array",
        msg="Runtime array produced by $split is a conversion failure",
        expression={"$toString": {"$split": ["a,b", ","]}},
        error_code=CONVERSION_FAILURE_ERROR,
    ),
    ExpressionTestCase(
        "type_runtime_object",
        msg="Runtime object produced by $mergeObjects is a conversion failure",
        expression={"$toString": {"$mergeObjects": [{"a": 1}]}},
        error_code=CONVERSION_FAILURE_ERROR,
    ),
]


@pytest.mark.parametrize("test", pytest_params(TOSTRING_TYPE_ERROR_TESTS))
def test_toString_type_errors(collection, test: ExpressionTestCase):
    """$toString rejects unsupported BSON types with a conversion failure."""
    result = execute_expression(collection, test.expression)
    assert_expression_result(
        result, expected=test.expected, error_code=test.error_code, msg=test.msg
    )
